### PR TITLE
support expiration

### PR DESCRIPTION
**Pull request by sunheehnus**
Related to https://github.com/RedisLabs/spark-redis/issues/11

### CODE REVIEW

**Comment by dvirsky** [comment]
Add this to all save methods please, and maybe a test for this? (i.e. save with expiration of a second, sleep 1.1 seconds then make sure the key is not there)

**Comment by sunheehnus** [comment]
Hi @dvirsky , already push the new commit :-)

**Comment by sunheehnus** [comment]
As it is just very simple, just merge it

**Comment by dvirsky** [comment]
looks good, thanks

**Comment by evbo** [comment]
Can this fix be implemented for setFixedList as well?

https://github.com/RedisLabs/spark-redis/blob/a1aa20e9d8745b5466ddc5bad5eccd657cc0ae8b/src/main/scala/com/redislabs/provider/redis/redisFunctions.scala#L376

**Pull request merged**
